### ISSUE TITLE
Connection to {MY_SOCKET_URL} was not upgraded to websocket

### ISSUE THREAD

**Issue by lionuncle** [dart-lang/web_socket_channel#164]
`
    channel = IOWebSocketChannel.connect(Uri.encode(MY_SOCKET_URL));
`
I'm listening to this channel and the snapshot returns

`WebSocketChannelException: WebSocketException: Connection to 'http://dev-system.worksamurai.com.au:0/api/websocket/messages/support?accessToken=oi+wBZblSq=&id=48#' was not upgraded to websocket`

**Comment by vishalsgithub** [comment]
Same Issue

**Comment by sopherwang** [comment]
I'm having the same iseue as well.  Did you find out the root of cause? Thanks

**Comment by birimkulov951** [comment]
any solutions?

**Comment by dazza5000** [comment]
This started popping up for me

**Comment by natebosch** [comment]
This looks like the server side is not upgrading the connection to a websocket. Stack Overflow is likely a better resource for specific implementation issues. You may need to post the specific request and response data to see what is going wrong.

**Comment by BhavyaRattan** [comment]
@natebosch I am facing the same issue as well, it works perfectly on postman so I doubt if it's from server-side, looks like a flutter specific issue as reported by many other devs: https://github.com/flutter/flutter/issues/11444

**Comment by natebosch** [comment]
From https://github.com/flutter/flutter/issues/11444#issuecomment-388391932 and https://github.com/dart-lang/sdk/issues/25120 it looks like it's most likely caused by a server that does not comply with the HTTP spec and the Dart SDK's behavior around lowercasing header names.

I'm not sure if we have a workaround for this - @brianquinlan do you know of any way to force certain header casing with the `dart:io` HTTP client and websocket implementation?

It may be feasible to implement the socket upgrade code yourself, with whatever quirks of header casing necessary to appease the buggy server, and then use `WebSocket.fromUpgradedSocket`. https://api.dart.dev/stable/2.16.0/dart-io/WebSocket/WebSocket.fromUpgradedSocket.html
